services:
  backend:
    build: ./backend
    container_name: inventory_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FRONTEND_URI: ${FRONTEND_URI}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: inventory_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env 
    environment:
      BACKEND_URI: ${BACKEND_URI}


volumes:
  postgres_data: